### PR TITLE
Trilomix mrb add delta

### PR DESCRIPTION
**Pull request by trilomix**
This change does not uptdate documentation but it's working.
You can add D+ and D+ from previous location with "%+d" and "%-d". 
It also add the time delta from previous location with "%Td"

Voily voilou,

Trilomix

### CODE REVIEW

**Comment by patrovite** [comment]
Hi, Thanks for the PR.
Currently I don't have a lot time to spend on the project so it will take a bit of time to test and include your PR on the master branch.
I also need to check that your tags are consistent with the exiting and the future tags (I don't think).

**Comment by patrovite** [comment]
Great job. Thanks for your PR.
I tested it. No problem.
If you what, send me by email (my email is in the about page) your name (or nickname) and website address to add in the about page.

**Comment by trilomix** [comment]
Hello,
I did a fix as I found error with the first roadbook mark. If we use the diff it's not initialized vs previous so I just Initialize it with the first point of the track. Minor change...
image

I also add rotation to the Label to be able to put more Label in less area.
The result look like this:
Third RoadBook
 I can chose angle and the reference point whit this interface:
image
I'll try to include documentation for this change and make a new pull request.

Best regards

**Comment by patrovite** [comment]
Great. 
I included your bug fix in the code.
For the label positioning and rotation you can generate a PR. I'll test it.
Don't worry for documentation. We can write it just after we merge your PR.

**Pull request merged**
