### PR TITLE
 Bugfix: The default format should use the selected unit 

### PR DESCRIPTION
**Pull request by FJBDev**

### CODE REVIEW

**Comment by patrovite** [comment]
Introducing the the selected unit in the GPX load function is not something I like because GPX files handle only metric system. 
You want to had the unit to a default mrb format string? Why not adding a new tags? 
%U => actif software unit
%Um=> metric unit
%Ui=> imperial unit

**Comment by FJBDev** [comment]
I'm not sure to understand what's the relationship with the GPX since the modification is only for the mini road book and it is only for displaying, it doesn't modify the GPX.

We could add a new tag but, as a user, I feel like if I have told CG to display everything in imperial, everything should be displayed in Imperial and I should not have to further modify more parameters.

But to me it's a bug. Let's take this example. You load your last 10km race GPX file in CG with CG configured in imperial.
The MRB will display 6 km as CG has been configured in imperial (6miles = 10km) but the default tag uses the letter "km".

**Comment by patrovite** [comment]
You add this:
"return "%N%L%A"+ Utils.uElev2String(settings.Unit) +"%L%D"+Utils.uLDist2String(settings.Unit)+"%L%H";"

Why not modifying the tags %A & %D to display the units! It's easier and it will work even whitout the default format.

**Comment by FJBDev** [comment]
Oh I understand now !

**Pull request merged**
